import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      id:1,
      name: 'Carlos',
      email: 'edcartech@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      id:2,
      name: 'Doris',
      email: 'doris@gmail.com',
      password: bcrypt.hashSync('123456'), 
      isAdmin: false,
    },
  ],
  images: [
    {
      id:1,
      name: 'SignIn',
      slug: 'signin',
      category: 'Shirts',
      image: '/assets/images/sliders/gps/1.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/1.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id:2,
      name: 'SignUp',
      slug: 'signup',
      category: 'Band',
      image: '/assets/images/sliders/gps/2.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/2.png',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Band',
    },
    {
      id:3,
      name: 'Reset Password',
      slug: 'reset-password',
      category: 'Bonnet',
      image: '/assets/images/sliders/gps/3.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/3.png',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Bonnet',
    },
    {
      id:4,
      name: 'Forgot Password',
      slug: 'forget-password',
      category: 'Band',
      image: '/assets/images/sliders/gps/4.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/4.png',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking Band',
    },
    {
      id:5,
      name: 'e-Recruitment',
      slug: 'e-recruit',
      category: 'Band',
      image: '/assets/images/sliders/gps/5.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/5.png',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Band',
    },


    {
      id:6,
      name: 'Login',
      slug: 'signin',
      category: 'Band',
      image: '/assets/images/sliders/gps/6.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/6.png',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Band',
    },
    {
      id:7,
      name: 'Signup',
      slug: 'signup',
      category: 'Band',
      image: '/assets/images/sliders/gps/7.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/7.png',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Band',
    },
    {
      id:8,
      name: 'Signup',
      slug: 'signup',
      category: 'Band',
      image: '/assets/images/sliders/gps/8.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/8.png',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Band',
    },
    {
      id:9,
      name: 'Signup',
      slug: 'signup',
      category: 'Band',
      image: '/assets/images/sliders/gps/9.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/9.png',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Band',
    },
    {
      id:10,
      name: 'Signup',
      slug: 'signup',
      category: 'Band',
      image: '/assets/images/sliders/gps/10.png',
      isFeatured: true,
      featuredImage: '/assets/images/sliders/gps/10.png',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Band',
    },
  ],
};
export default data;
//   image: '/assets/images/sliders/product6.jpg',
//https://swiperjs.com/demos/images/nature-8.jpg
